version: '3'

services:
  redis-db:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data

  message-queue:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  custom-emoji-api:
    image: api:1.0.0
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - REDIS_DB=1
      - RABBITMQ_HOST=message-queue
      - RABBITMQ_PORT=5672
    depends_on:
      - message-queue
      - redis-db
      - task-worker

  task-worker:
    image: worker:1.0.0
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - REDIS_DB=1
      - RABBITMQ_HOST=message-queue
      - RABBITMQ_PORT=5672
    command: celery -A worker.tasks worker
    depends_on:
      - message-queue
      - redis-db

  task-queue-dashboard:
    image: worker:1.0.0
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - RABBITMQ_HOST=message-queue
      - RABBITMQ_PORT=5672
      - FLOWER_UNAUTHENTICATED_API=true
    command: celery -A worker.tasks flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - custom-emoji-api
      - redis-db
      - task-worker