apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: custom-emoji-api
  name: custom-emoji-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: custom-emoji-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/custom-emoji-app-default: "true"
        io.kompose.service: custom-emoji-api
    spec:
      containers:
        - env:
            - name: RABBITMQ_HOST
              value: message-queue
            - name: RABBITMQ_PORT
              value: "5672"
            - name: REDIS_DB
              value: "1"
            - name: REDIS_HOST
              value: redis-db
            - name: REDIS_PORT
              value: "6379"
          image: api:1.0.0
          name: custom-emoji-api
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
